name: Docker Image CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  push_to_rigistry:
    name: Rerun Docker compose in server
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: SSH 
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name : SSH into digital ocean server
        run : ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_IP }} "chmod +x /root/switchr_commands.sh && /root/switchr_commands.sh"

            
        