name: Docker Image CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  run_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Rerun docker compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        command_timeout: 30m
        script: | 
          ./switchr_commands.sh
        